app = "deprembot-gokhan"
kill_signal = "SIGINT"
kill_timeout = 5

[build]

[env]
  PYTHONUNBUFFERED = "TRUE"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
